version: '3.9'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: app_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  clone_db:
    image: postgres:15
    environment:
      POSTGRES_DB: clone_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5434:5432"
    volumes:
      - clone_pgdata:/var/lib/postgresql/data

  fastapi_app:
    build: .
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: app_db
      DB_USER: postgres
      DB_PASSWORD: postgres
    ports:
      - "8000:8000"
    volumes:
      - ./logs:/app/logs

  spammer:
    build:
      context: .
      dockerfile: Dockerfile.spammer
    depends_on:
      - fastapi_app
    environment:
      - FASTAPI_URL=http://fastapi_app:8000/create_transaction

  batch_sync:
    build:
      context: .
      dockerfile: Dockerfile.sync
    depends_on:
      - db
      - clone_db
    environment:
      PROD_DB_HOST: db
      PROD_DB_PORT: 5432
      PROD_DB_NAME: app_db
      PROD_DB_USER: postgres
      PROD_DB_PASSWORD: postgres

      CLONE_DB_HOST: clone_db
      CLONE_DB_PORT: 5432
      CLONE_DB_NAME: clone_db
      CLONE_DB_USER: postgres
      CLONE_DB_PASSWORD: postgres

  init_db:
    build: .
    depends_on:
      - db
    command: [ "python", "init_db.py" ]

volumes:
  pgdata:
  clone_pgdata:
